// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNnZg0HJc2_L5goz-SUFrrWCeqVU7wIok',
    appId: '1:563722881205:web:9c1f4496f1a3b534ebd6fc',
    messagingSenderId: '563722881205',
    projectId: 'mta-water-delivery-8697f',
    authDomain: 'mta-water-delivery-8697f.firebaseapp.com',
    databaseURL: 'https://mta-water-delivery-8697f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mta-water-delivery-8697f.firebasestorage.app',
    measurementId: 'G-WWLSVF16Q8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgW4JFdN_SgtTRt_cNbqxv-GbWJEQNRCk',
    appId: '1:563722881205:android:21ed4298bb00ab1aebd6fc',
    messagingSenderId: '563722881205',
    projectId: 'mta-water-delivery-8697f',
    databaseURL: 'https://mta-water-delivery-8697f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mta-water-delivery-8697f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0Lyl1sWOzUWYeuiL-GzCC7KyQWn8S0lc',
    appId: '1:563722881205:ios:bac5d0050ec42667ebd6fc',
    messagingSenderId: '563722881205',
    projectId: 'mta-water-delivery-8697f',
    databaseURL: 'https://mta-water-delivery-8697f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mta-water-delivery-8697f.firebasestorage.app',
    androidClientId: '563722881205-mc4loc3i34thn7vuoto36kuuo19is461.apps.googleusercontent.com',
    iosClientId: '563722881205-6kfj4udcuei6f40j5dvraabqtosl4r38.apps.googleusercontent.com',
    iosBundleId: 'com.example.mtaWaterDelivery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0Lyl1sWOzUWYeuiL-GzCC7KyQWn8S0lc',
    appId: '1:563722881205:ios:bac5d0050ec42667ebd6fc',
    messagingSenderId: '563722881205',
    projectId: 'mta-water-delivery-8697f',
    databaseURL: 'https://mta-water-delivery-8697f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mta-water-delivery-8697f.firebasestorage.app',
    androidClientId: '563722881205-mc4loc3i34thn7vuoto36kuuo19is461.apps.googleusercontent.com',
    iosClientId: '563722881205-6kfj4udcuei6f40j5dvraabqtosl4r38.apps.googleusercontent.com',
    iosBundleId: 'com.example.mtaWaterDelivery',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDNnZg0HJc2_L5goz-SUFrrWCeqVU7wIok',
    appId: '1:563722881205:web:87ac1acc24d63629ebd6fc',
    messagingSenderId: '563722881205',
    projectId: 'mta-water-delivery-8697f',
    authDomain: 'mta-water-delivery-8697f.firebaseapp.com',
    databaseURL: 'https://mta-water-delivery-8697f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mta-water-delivery-8697f.firebasestorage.app',
    measurementId: 'G-ZJHSCXPZBZ',
  );

}